### ISSUE TITLE
syntax highlighting bug on objective c file

### ISSUE THREAD

**Issue by izuzak** [atom/language-objective-c#7] opened 2015-03-24 11:16 UTC
_From @scgaw2000 on March 24, 2015 5:40_

The double quotation mark after a backslash is not the end of NSString construction. As a result, the following code should be highlighted as 

```objective-c++
if (![string isEqualToString:@"\t\n\"123") {
	// do somthing
}
```

but not
![screen shot 2015-03-24 at 13 27 02](https://cloud.githubusercontent.com/assets/3814422/6796279/05410c06-d22b-11e4-8458-b9462ad1933d.png)

Using version 0.187.0 (0.187.0) on OS X 10.0.3 beta

_Copied from original issue: atom/atom#6080_

**Comment by scgaw2000** [comment] 2015-04-02 16:48
The cause of this bug is that the ```string_escaped_char``` is not loaded from ```source.c```.

if we replace 
```
      {
        'include': 'source.c#string_escaped_char'
      }

```
with 
```
      {
        'match': '\\\\(\\\\|[abefnprtv\'"?]|[0-3]\\d{,2}|[4-7]\\d?|x[a-fA-F0-9]{,2}|u[a-fA-F0-9]{,4}|U[a-fA-F0-9]{,8})'
        'name': 'constant.character.escape.c'
      }
      {
        'match': '\\\\.'
        'name': 'invalid.illegal.unknown-escape.c'
      }
```
, then everything works fine.

P.S. Not only the ```source.c#string_escaped_char``` is not loaded, and also ```source.c#string_placeholder``` is not loaded either. 

![untitled](https://cloud.githubusercontent.com/assets/3814422/6968473/bc4c99e0-d999-11e4-970c-12059ca4c645.gif)

Perhaps this bug is not related to the content of grammar file but how atom parse the grammar file.

**Comment by scgaw2000** [comment] 2015-04-02 16:50
The cause of this bug is that the ```string_escaped_char``` is not loaded from ```source.c```.

if we replace 
```
      {
        'include': 'source.c#string_escaped_char'
      }

```
with 
```
      {
        'match': '\\\\(\\\\|[abefnprtv\'"?]|[0-3]\\d{,2}|[4-7]\\d?|x[a-fA-F0-9]{,2}|u[a-fA-F0-9]{,4}|U[a-fA-F0-9]{,8})'
        'name': 'constant.character.escape.c'
      }
      {
        'match': '\\\\.'
        'name': 'invalid.illegal.unknown-escape.c'
      }
```
, then everything works fine.

Not only the ```source.c#string_escaped_char``` is not loaded, and also ```source.c#string_placeholder``` is not loaded. 

![untitled](https://cloud.githubusercontent.com/assets/3814422/6968473/bc4c99e0-d999-11e4-970c-12059ca4c645.gif)

Perhaps this bug is not related to the content of grammar file but how atom parse the grammar file.

**Comment by scgaw2000** [comment] 2015-04-02 19:12
I checked http://manual.macromates.com/en/language_grammars#language_rules, which doesn't show that include can be used for referencing rules, such as ```#string_escaped_char'``` in source.c file. So I replace these includes with the rules in source.c file.

**Comment by 50Wliu** [comment] 2015-12-02 03:37
I can't reproduce this using the language-objective-c v0.15.0 and language-c v0.50.1, so closing.

**Closed by 50Wliu** 2015-12-02 03:37 UTC
Labels: bug
